pokedex/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers

from . import views


router = routers.DefaultRouter()
router.register("pokemons", views.PokemonsViewSet, basename="api-pokemon")

app_name = "pokedex"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.PokemonView.as_view(), name="pokemon-detail"),
    path("<int:pk>/edit/", views.PokemonEditView.as_view(), name="pokemon-edit"),
    path("<int:pk>/delete/", views.PokemonDeleteView.as_view(), name="pokemon-delete"),
    path("create/", views.PokemonCreateView.as_view(), name="pokemon-create"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),

    # REST API
    path("api/", include(router.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pokesite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pokedex/', include("pokedex.urls")),
    path('pokedex/api-auth/', include('rest_framework.urls')),
    path('', RedirectView.as_view(url="pokedex/"))
]

pokedex/models.py
from django.db import models

# Create your models here.
class PokemonType(models.Model):
    name = models.CharField(max_length=100, unique=True)
    def __str__(self):
        return self.name

class Ability(models.Model):
    name = models.CharField(max_length=100, unique=True)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "Abilities"

class Pokemon(models.Model):
    national_pokedex_number = models.SmallIntegerField(unique=True, blank=True, null=True)
    name = models.CharField(max_length=100, unique=True)
    sprite_slug = models.CharField(max_length=100, blank=True, null=True)
    types = models.ManyToManyField(PokemonType, through="PokemonHasType")
    abilities = models.ManyToManyField(Ability)
    is_deleted = models.BooleanField(default=False)
    def __str__(self):
        return self.name
    @property
    def nationalPokedexNum(self):
        if self.national_pokedex_number:
            return str(self.national_pokedex_number).zfill(4)
        return "custom"
    class Meta:
        ordering = ["id"]

class PokemonHasType(models.Model):
    pokemon = models.ForeignKey(Pokemon, on_delete=models.CASCADE)
    pokemon_type = models.ForeignKey(PokemonType, on_delete=models.CASCADE, blank=True, null=True)
    slot = models.SmallIntegerField()
    def __str__(self):
        return f"slot {self.slot} {self.pokemon_type}"

class Stat(models.Model):
    pokemon = models.ForeignKey(Pokemon, related_name="stats", on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    base_stat = models.SmallIntegerField()
    def __str__(self):
        return self.name

pokedex/forms.py
from django import forms

from pokedex.models import Ability, PokemonType

class PokemonEditForm(forms.Form):
    name = forms.CharField(max_length=100)

    type1 = forms.ModelChoiceField(
        queryset=PokemonType.objects.order_by("name"),
        required=True,
        label="Type",
        to_field_name="name")
    type2 = forms.ModelChoiceField(
        queryset=PokemonType.objects.order_by("name"),
        required=False,
        label="Type",
        to_field_name="name")

    ability1 = forms.ModelChoiceField(
        queryset=Ability.objects.order_by("name"),
        required=True,
        label="Ability",
        to_field_name="name")
    ability2 = forms.ModelChoiceField(
        queryset=Ability.objects.order_by("name"),
        required=False,
        label="Ability",
        to_field_name="name")
    ability3 = forms.ModelChoiceField(
        queryset=Ability.objects.order_by("name"),
        required=False,
        label="Ability",
        to_field_name="name")

    hp              = forms.IntegerField(min_value=0)
    attack          = forms.IntegerField(min_value=0)
    defense         = forms.IntegerField(min_value=0)
    special_attack  = forms.IntegerField(min_value=0)
    special_defense = forms.IntegerField(min_value=0)
    speed           = forms.IntegerField(min_value=0)

pokedex/views.py
from django.http import HttpRequest, HttpResponse
from django.urls import reverse
from django.views import View, generic
from django.contrib.auth import login, views as auth_views
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Permission, User
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator
from rest_framework import viewsets

from pokedex.forms import PokemonEditForm
from pokedex.models import Pokemon, PokemonType
from pokedex.serializers import PokemonSerializer
from pokedex.utils import create_pokemon, update_pokemon

# Create your views here.
class LoginView(auth_views.LoginView):
    template_name = "pokedex/login.html"
    next_page = "/"
    redirect_authenticated_user = True

class LogoutView(auth_views.LogoutView):
    next_page = "/"

class RegisterView(View):
    template_name = "pokedex/register.html"
    form_class = UserCreationForm

    def get(self, request: HttpRequest):
        if request.user.is_authenticated:
            return redirect("/")
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request: HttpRequest):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
                form.cleaned_data["username"],
                password=form.cleaned_data["password1"])
            user.user_permissions.set([
                Permission.objects.get(codename="add_pokemon"),
                Permission.objects.get(codename="view_pokemon"),
                Permission.objects.get(codename="change_pokemon"),
                Permission.objects.get(codename="delete_pokemon"),
            ])
            login(request, user)
            return redirect("pokedex:index")
        else:
            return render(request, self.template_name, {"form": form})

class IndexView(View):
    template_name = "pokedex/index.html"

    def get(self, request: HttpRequest):
        pokemon_type = request.GET.get("type")
        pokemons = Pokemon.objects.filter(is_deleted=False)
        if pokemon_type != "all" and pokemon_type != None:
            pokemons = pokemons.filter(types__name=pokemon_type)
        context = {
            "pokemons": pokemons,
            "types": PokemonType.objects.order_by("name")
        }
        return render(request, self.template_name, context)

class PokemonView(View):
    queryset = Pokemon.objects.filter(is_deleted=False)
    template_name = "pokedex/pokemon_details.html"

    def get(self, request, pk):
        pokemon = self.queryset.get(pk=pk)

        prev_pokemon = self.queryset.filter(pk=pk-1)
        prev_pokemon = prev_pokemon.first() if prev_pokemon.exists() else None
        next_pokemon = self.queryset.filter(pk=pk+1)
        next_pokemon = next_pokemon.first() if next_pokemon.exists() else None

        context = {
            "pokemon": pokemon,
            "prev_pokemon": prev_pokemon,
            "next_pokemon": next_pokemon
        }

        return render(request, self.template_name, context)

class PokemonEditView(View):
    template_name = "pokedex/pokemon_edit.html"
    form_class = PokemonEditForm

    @method_decorator(never_cache)
    def get(self, request, pk):
        pokemon = get_object_or_404(Pokemon, pk=pk)

        initial_form_data = {"name": pokemon.name,}
        for i, type_ in enumerate(pokemon.types.all()):
            initial_form_data[f"type{i+1}"] = type_.name
        for i, ability in enumerate(pokemon.abilities.all()):
            initial_form_data[f"ability{i+1}"] = ability.name
        for stat in pokemon.stats.all():
            initial_form_data[stat.name.replace("-", "_")] = stat.base_stat

        form = self.form_class(initial_form_data)

        return render(request, self.template_name, {"pokemon": pokemon, "form": form})

    def post(self, request: HttpRequest, pk):
        pokemon = get_object_or_404(Pokemon, pk=pk)

        if not request.user.is_authenticated:
            return render(request, self.template_name, {"pokemon": pokemon})

        if not request.user.has_perm("pokedex.change_pokemon"):
            return render(request, self.template_name, status=403)

        form = self.form_class(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get("name")

            if Pokemon.objects.filter(name=name).exists() and pokemon.name != name:
                form.add_error("name", f"{name} already exists. Pokemon name must be unique")
                return render(request, self.template_name, {"pokemon": pokemon, "form": form})

            pokemon = update_pokemon(pokemon, **form.cleaned_data)

            return redirect("pokedex:pokemon-detail", pk=pokemon.pk)
        else:
            return render(request, self.template_name, {"pokemon": pokemon, "form": form})

class PokemonCreateView(View):
    template_name = "pokedex/pokemon_create.html"
    form_class = PokemonEditForm

    @method_decorator(never_cache)
    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request: HttpRequest):
        form = self.form_class(request.POST)

        if not request.user.is_authenticated:
            return render(request, self.template_name)

        if not request.user.has_perm("pokedex.add_pokemon"):
            return render(request, self.template_name, status=403)

        if form.is_valid():
            name = form.cleaned_data.get("name")

            if Pokemon.objects.filter(name=name).exists():
                form.add_error("name", f"{name} already exists. Pokemon name must be unique")
                return render(request, self.template_name, {"form": form})

            pokemon = create_pokemon(**form.cleaned_data)

            return redirect("pokedex:pokemon-detail", pk=pokemon.pk)
        else:
            return render(request, self.template_name, {"form": form})

class PokemonDeleteView(View):
    def post(self, request: HttpRequest, pk):
        if not request.user.has_perm("pokedex.delete_pokemon"):
            return redirect(reverse("pokedex:pokemon-detail", args=[pk]))

        if not request.user.is_authenticated:
            return redirect("pokedex:login")
        pokemon = get_object_or_404(Pokemon, pk=pk)
        pokemon.is_deleted = True
        pokemon.save()
        return redirect("pokedex:index")


# Djano REST Framework
class PokemonsViewSet(viewsets.ModelViewSet):
    queryset = Pokemon.objects.filter(is_deleted=False)
    serializer_class = PokemonSerializer

    def perform_destroy(self, instance: Pokemon):
        instance.is_deleted = True
        instance.save()

pokedex/templates/pokedex/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Pokedex{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'pokedex/css/style.css' %}">
</head>
<body>
    {% include 'pokedex/navbar.html' %}
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    {% include 'pokedex/footer.html' %}
</body>
</html>

pokedex/templates/pokedex/footer.html
<footer class="flex-col-center">
    <span>Pokemon data from <a href="https://pokeapi.co/">PokéAPI</a></span>
</footer>

pokedex/templates/pokedex/index.html
{% extends "pokedex/base.html" %}

{% block title %}
    Pokemons | Pokedex
{% endblock %}

{% block content %}
    {% if pokemons %}
        <div class="mb-4 space-between">
            {% include 'pokedex/pokemon_type_filter.html' %}
            <div>
                {% with count=pokemons.count %}
                    <span class="font-bold">{{ count }}</span> pokemon{{ count | pluralize }}
                {% endwith %}
            </div>
        </div>
        <div class="pokemon-grid">
        {% for pokemon in pokemons %}
                <div class="pokemon-box">
                    <a href="{% url 'pokedex:pokemon-detail' pokemon.pk %}">
                        <div class="pokemon-pokedex-number">[{{ pokemon.nationalPokedexNum }}]</div>
                        <div class="pokemon-name">{{ pokemon.name | capfirst }}</div>
                        {% if pokemon.sprite_slug %}
                            <img src="{{ pokemon.sprite_slug }}">
                        {% else %}
                            <div class="no-sprite">[no pic.]</div>
                        {% endif %}
                    </a>
                    <div class="types">
                        {% for type in pokemon.types.all %}
                            <span class="pokemon-type {{ type.name }}">{{ type.name }}</span>
                        {% endfor %}
                    </div>
                </div>
        {% endfor %}
        </div>
    {% else %}
    <h1>No pokemons :(</h1>
    {% endif %}
{% endblock %}

pokedex/templates/pokedex/login.html
{% extends "pokedex/base.html" %}

{% block title %}
    Login | Pokedex
{% endblock %}

{% block content %}
    <div class="flex-col-center">
        <h1>Login to Pokedex!</h1>
        <form action="" method="post" >
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Log in!" >
        </form>
    </div>
{% endblock %}

pokedex/templates/pokedex/navbar.html
<div id="navbar" class="mb-4">
    <div id="nav-left">
        <a class="nav-link" href="{% url 'pokedex:index' %}"><b>Pokedex</b></a> |
        <a class="nav-link" href="{% url 'pokedex:pokemon-create' %}">Create a Pokemon!</a>
    </div>
    <div id="nav-right">
        {% if user.is_anonymous %}
            <a class="nav-link" href="{% url 'pokedex:register' %}">Register</a>
            <a class="nav-link" href="{% url 'pokedex:login' %}">Login</a>
        {% elif user.is_authenticated %}
            <span>Logged in as: <b>{{ user.username }}</b></span> |
            <form action="{% url 'pokedex:logout' %}" method="post">
                {% csrf_token %}
                <input class="plain-btn" type="submit" value="logout" >
            </form>
        {% endif %}
    </div>
</div>

pokedex/templates/pokedex/pokemon-delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

pokedex/templates/pokedex/pokemon_create.html
{% extends "pokedex/base.html" %}

{% block title %}
    Create Pokemon | Pokedex
{% endblock %}

{% block content %}
    <div class="flex-col-center">
        <h1>Create a Pokemon!</h1>
        {% if user.is_anonymous %}
            <div>
                <p>You need to login before creating a Pokemon.</p>
                <a href="{% url 'pokedex:login' %}?next={{ request.path }}">Login</a> to create a Pokemon!
            </div>
        {% elif not perms.pokedex.add_pokemon %}
            <div>
                <p>You do not have the appropriate permission to create a pokemon.</p>
            </div>
        {% elif user.is_authenticated %}
            <form action="{% url 'pokedex:pokemon-create' %}" method="post" >
                {% csrf_token %}
                {{ form }}
                <input class="mt-4" type="submit" value="Create!">
                <a href="{% url 'pokedex:index' %}">Cancel</a>
            </form>
        {% endif %}
    </div>
{% endblock %}

pokedex/templates/pokedex/pokemon_details.html
{% extends "pokedex/base.html" %}

{% block title %}
    {{ pokemon.name | capfirst }} Details | Pokedex
{% endblock%}

{% block content %}
    <div class="flex-col-center">
        <span>[{{ pokemon.nationalPokedexNum }}]</span>
        <h1>{{ pokemon.name | capfirst }}</h1>
        {% if pokemon.sprite_slug %}
            <img src="{{ pokemon.sprite_slug }}">
        {% else %}
            <div class="no-sprite outline">[no pic.]</div>
        {% endif %}

        <h2>Type</h2>
        <div>
            {% for type in pokemon.types.all %}
                <span class="pokemon-type {{ type.name }}">{{ type.name }}</span>
            {% endfor %}
        </div>

        <h2>Abilities</h2>
        <div class="flex-col-center">
            {% for ability in pokemon.abilities.all %}
                <span>{{ ability.name | capfirst }}</span>
            {% endfor %}
        </div>

        <h2>Stats</h2>
        <div class="mb-4">
            {% for stat in pokemon.stats.all %}
                {{ stat.name }}: <b>{{ stat.base_stat }}</b>
            {% endfor %}
        </div>

        <div>
            {% if user.is_anonymous %}
                <a class="mb-2" href="#">edit</a>
                <span>(login required)</span>
            {% elif user.is_authenticated %}
                <a class="mb-2" href="{% url 'pokedex:pokemon-edit' pokemon.pk %}">edit</a>
            {% endif %}
        </div>

        <div>
            {% if user.is_anonymous %}
                <input class="plain-btn" type="submit" value="delete">
                <span>(login required)</span>
            {% elif user.is_authenticated %}
                <form action="{% url 'pokedex:pokemon-delete' pokemon.pk %}" method="post">
                    {% csrf_token %}
                    <input class="plain-btn" type="submit" value="delete" onclick="return confirm('Confirm deletion: {{ pokemon.name | capfirst }}')">
                </form>
            {% endif %}
        </div>

        <div class="mt-4">
            <div>
                {% if prev_pokemon %}
                    <a href="{% url 'pokedex:pokemon-detail' prev_pokemon.pk %}"><< {{ prev_pokemon }}</a>
                {% endif %}
                {% if next_pokemon %}
                    <a href="{% url 'pokedex:pokemon-detail' next_pokemon.pk %}">{{ next_pokemon }} >></a>
                {% endif %}
            </div>
        </div>

        <a class="mt-4" href="{% url 'pokedex:index' %}">home</a>
    </div>
{% endblock %}

pokedex/templates/pokedex/pokemon_edit.html
{% extends "pokedex/base.html" %}

{% block title %}
    Edit {{ pokemon.name | capfirst }} | Pokedex
{% endblock %}

{% block content %}
    <div class="flex-col-center">
        {% if pokemon %}
            <h1>Edit: [{{ pokemon.nationalPokedexNum }}] {{ pokemon.name | capfirst }}</h1>
        {% else %}
            <h1>Edit Pokemon</h1>
        {% endif %}
        <img src="{{ pokemon.sprite_slug }}">
        {% if user.is_anonymous %}
            <div>
                <p>You need to login before editing a Pokemon.</p>
                <a href="{% url 'pokedex:login' %}?next={{ request.path }}">Login</a> to edit Pokemon!
            </div>
        {% elif not perms.pokedex.change_pokemon %}
            <div>
                <p>You do not have the appropriate permission to edit pokemon</p>
            </div>
        {% elif user.is_authenticated %}
            <form action="{% url 'pokedex:pokemon-edit' pokemon.pk %}" method="post">
                {% csrf_token %}
                {{ form.errors }}
                {% for field in form %}
                    <div>
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %}
                <input class="mt-4" type="submit" value="Submit">
                <a href="{% url 'pokedex:pokemon-detail' pokemon.pk %}">Cancel</a>
            </form>
        {% endif %}
    </div>
{% endblock %}

pokedex/templates/pokedex/pokemon_type_filter.html
<form action="{% url 'pokedex:index' %}" method="get">
    <select name="type" onchange="this.form.submit()">
        <option value="all">All</option>
        {% for type in types %}
            {% if type.name == request.GET.type %}
                <option class="{{ type.name }}" selected value="{{ type.name }}">{{ type.name }}</option>
            {% else %}
                <option class="{{ type.name }}" value="{{ type.name }}">{{ type.name }}</option>
            {% endif %}
        {% endfor %}
    </select>
</form>

pokedex/templates/pokedex/register.html
{% extends "pokedex/base.html" %}

{% block title %}
    Register | Pokedex
{% endblock %}

{% block content %}
    <div class="flex-col-center">
        <h1>Register</h1>
        <form action="{% url 'pokedex:register' %}" method="post">
            {% csrf_token %}
            {{ form.errors }}
            {% for field in form %}
                <div>
                    {{ field.label_tag }}
                    {{ field }}
                </div>
            {% endfor %}
            <input class="mt-4" type="submit" value="Submit">
        </form>
    </div>
{% endblock %}